---
- name: Install Nokogiri requirements
  apt:
    pkg:
      - libxslt1-dev
      - libxml2-dev
      - zlib1g-dev
    state: latest

- name: Add APT Public Key for Yarn
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Add APT Repository for Yarn
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present

- name: Install Yarn and NodeJS
  apt:
    update_cache: yes
    name: yarn
    install_recommends: yes # nodejs
    state: latest

- name: Install Bundler as a system gem
  gem:
    name: bundler
    user_install: no
    version: '{{ bundler_version }}'
    state: present

- name: Create directory for app
  file:
    state: directory
    path: '/srv/{{ app_name }}'
    owner: '{{ deployer }}'
    group: '{{ deployer }}'

- name: Create Shared Directory to Bootstrap Capistrano
  file:
    state: directory
    path: '/srv/{{ app_name }}/shared'
    owner: '{{ deployer }}'
    group: '{{ deployer }}'

- name: App Directory | tmp
  file:
    state: directory
    path: '/srv/{{ app_name }}/shared/tmp'
    owner: '{{ deployer }}'
    group: '{{ deployer }}'

- name: App Directory | tmp/cache
  file:
    state: directory
    path: '/srv/{{ app_name }}/shared/tmp/cache'
    owner: '{{ deployer }}'
    group: '{{ deployer }}'

- name: App Directory | tmp/sockets
  file:
    state: directory
    path: '/srv/{{ app_name }}/shared/tmp/sockets'
    owner: '{{ deployer }}'
    group: '{{ deployer }}'

- name: App Directory | tmp/pids
  file:
    state: directory
    path: '/srv/{{ app_name }}/shared/tmp/pids'
    owner: '{{ deployer }}'
    group: '{{ deployer }}'

- name: Symlink Rails logs to common area
  file:
    src: '/srv/{{ app_name }}/shared/log'
    dest: '/var/log/rails'
    state: link
    force: yes

- name: Create Bundler Directory
  file:
    path: '/home/{{ deployer }}/.bundle'
    state: directory
    owner: '{{ deployer }}'
    group: '{{ deployer }}'

- name: Configure Bundler
  template:
    src: templates/bundler.j2
    dest: '/home/{{ deployer }}/.bundle/config'
    mode: '0644'
    owner: '{{ deployer }}'
    group: '{{ deployer }}'

- name: Fetch SSH host keys for {{ deployment_host }}
  command: ssh-keyscan -t rsa {{ deployment_host }}
  register: deployment_host_key

- name: Install SSH host keys for {{ deployment_host }}
  known_hosts:
    name: '{{ deployment_host }}'
    state: present
    key: '{{ deployment_host_key.stdout }}'
