---
- name: Install Nokogiri requirements
  apt:
    pkg:
      - libxslt1-dev
      - libxml2-dev
    state: latest

- name: Install Ruby FFI
  apt:
    pkg:
      - libffi6
      - libffi-dev
    state: latest

- name: Install Bundler as a system gem
  gem:
    name: bundler
    user_install: no
    version: '{{ bundler_version }}'
    state: present

- name: Create directory for app
  file:
    state: directory
    path: '/srv/{{ app_name }}'
    owner: '{{ deployer }}'
    group: '{{ deployer }}'

- name: Create Shared Directory to Bootstrap Capistrano
  file:
    state: directory
    path: '/srv/{{ app_name }}/shared'
    owner: '{{ deployer }}'
    group: '{{ deployer }}'

- name: Symlink Rails logs to common area
  file:
    src: '/srv/{{ app_name }}/shared/log'
    dest: '/var/log/rails'
    state: link
    force: yes

- name: Fetch SSH host keys for {{ deployment_host }}
  command: ssh-keyscan -t rsa {{ deployment_host }}
  register: deployment_host_key

- name: Install SSH host keys for {{ deployment_host }}
  known_hosts:
    name: '{{ deployment_host }}'
    state: present
    key: '{{ deployment_host_key.stdout }}'
